---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: sales-events-consumer-trigger-auth
  namespace: sales-events-consumer-ns
spec:
  podIdentity:
    provider: aws-eks
---
apiVersion: keda.sh/v1alpha1 # https://keda.sh/docs/2.0/concepts/scaling-deployments/
kind: ScaledObject
metadata:
  name: sales-events-consumer-scaler
  namespace: sales-events-consumer-ns
  labels:
    app: sales-events-consumer
    deploymentName: sales-events-consumer
spec:
  scaleTargetRef:
    kind: Deployment
    name: sales-events-consumer
  minReplicaCount: 1
  maxReplicaCount: 50
  pollingInterval: 10
  cooldownPeriod:  500
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: https://sqs.eu-west-1.amazonaws.com/111122223333/reliable_message_q
      queueLength: "10"
      awsRegion: "eu-west-1"
      identityOwner: pod
    authenticationRef:
      name: sales-events-consumer-trigger-auth
---